---
name: Find Unused Files
author: MongoDB Realm Docs Team
description: Find unused files in a snooty source directory.
branding:
  icon: trash-2
  color: green
inputs:
  source:
    description: "The path to the source directory."
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        DOCDOCTOR_DIR="${{ github.action_path }}"/../..
        pushd "$DOCDOCTOR_DIR"
        npm ci
        npm run build
        popd
        RESULT=`node "$DOCDOCTOR_DIR" findUnused "${{ inputs.source }}"`
        if [[ -z "$RESULT" ]]; then
          echo "No unused files found."
          exit 0
        else
          echo "Unused files found:"
          echo $RESULT
          echo
          echo 'Possible remediations:'
          echo '- Delete the unused file.'
          echo '- Add the file to a toctree.'
          echo '- If the file is intentionally orphaned from a toctree, rename it index.txt and move it into a new directory with the desired page name. (e.g. deliberate-orphan.txt -> deliberate-orphan/index.txt)'
          echo '- If the file is not actually part of the site (such as a source file used to generate an image), move it out of the ${{ inputs.source }} directory.'
          exit 1
        fi
